### ISSUE TITLE
Setar uma versão 1.x

### ISSUE THREAD

**Issue by sergiors** [Coderockr/silex-mongodb-provider#2]
Olá, o silex 2 acabou de sair, acho valido setar como como 1.0.0-alpha pelo menos e cria uma branch 1.x

e deixar a master já para suportar a nova versão..

\cc @eminetto

**Comment by eminetto** [comment]
No composer.json tem isso:

"require": {
        "php": ">=5.4",
        "silex/silex": "~1.3",
        "mongodb/mongodb": "^1.0.0@beta"
    },

Será que não resolve? Eu não cheguei a testar :)

**Comment by sergiors** [comment]
@eminetto um branch já resolve, estava vendo aqui, ex: `1.x` dai no composer fica `"coderockr/silex-mongodb-provider": "1.x-dev"`

vou fazer o PR para suportar a nova versão

**Comment by sergiors** [comment]
Outro pronto, no composer ta com suporte a versão `>=5.4`, se rodar o ambiente de teste nessa versão, vai dar pau, o `phpunit 5.x` requerer `>=5.6`

**Comment by eminetto** [comment]
Criei a branch 1.3, seguindo o exemplo do https://github.com/silexphp/Silex. 

Valeu @sergiors
